\r [ sequenci de escpe [ ch\r ]
2130 [ constnte ineteir deciml ] [ int ]
-123 [ constante inteira decimal ] [ int ]
33.28 [ constante de ponto flutuante  ] [ double  ]
0XF [ constante inteira hexadecimal ] [ int ]
0101 [ constante inteira octal ] [ int ]
2.0e30 [ constante de ponto flutuante "notação científica" ] [ double ]
\xDC [ sequencia de escape hexadecimal ] [ char ]
'\"' [ constante string ] [ char ]
'\\' [ constante de caractere ] [ int ]
'F' [  constante de caractere  ] [  int  ]
0 [ constante inteira decimal ] [ int ]
'\0' [ constante de caractere/ caractere nulo ] [ int]
"F" [ constante string ] [ char ]
-4567.89 [ constante de ponto flutuante ] [ double ]